In [25]:
# working with numpy libraries
import numpy as np
import pandas as pd

In [10]:
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("Number Average:", arr.mean())
print("Total number:", arr.sum())
print("Square of the element:", arr ** 2)

Array: [10 20 30 40 50]
Number Average: 30.0
Total number: 150
Square of the element: [ 100  400  900 1600 2500]


In [17]:
# woking with students score using numpy array
scores = np.array([
    [78, 85, 90],
    [88, 92, 80],
    [70, 75, 85],
    [95, 90, 88],
    [60, 65, 70],
    [85, 80, 82],
    [72, 78, 88],
    [90, 95, 92]
])

print("\nStudent Scores\n", scores)

#Average score per student
print("\nAverage score per student\n", scores.mean(axis=1))

#Average score per subject
print("\nAverage score per subject\n", scores.mean(axis=0))

#Highest score per subject
highest_score = scores.max(axis=0)
print("\nHighest score per subject\n", highest_score)


Student Scores
 [[78 85 90]
 [88 92 80]
 [70 75 85]
 [95 90 88]
 [60 65 70]
 [85 80 82]
 [72 78 88]
 [90 95 92]]

Average score per student
 [84.33333333 86.66666667 76.66666667 91.         65.         82.33333333
 79.33333333 92.33333333]

Average score per subject
 [79.75  82.5   84.375]

Highest score per subject
 [95 95 92]


In [23]:
science_score = scores[:, 2]
score_above_90 = np.where(science_score > 90)[0]
print("\nStudent science above 90\n", score_above_90 + 1)


Student science above 90
 [8]


In [27]:
# working pandas dataframe
#sample dataset
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Department": ["HR", "IT", "IT", "Finance", "HR"],
    "Salary": [50000, 60000, 55000, 65000, np.nan],
    "Age": [25, 30, 28, 40, 35]
}

df = pd.DataFrame(data)
print("\DataFrame\n", df)

\DataFrame
       Name Department   Salary  Age
0    Alice         HR  50000.0   25
1      Bob         IT  60000.0   30
2  Charlie         IT  55000.0   28
3    David    Finance  65000.0   40
4      Eve         HR      NaN   35


In [29]:
#filter employee that's greater 30
filter_df = df[df['Age'] > 30]
print(filter_df)

    Name Department   Salary  Age
3  David    Finance  65000.0   40
4    Eve         HR      NaN   35
